# Generated by Django 5.1.4 on 2024-12-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_booking_id_alter_contact_us_id_alter_hotel_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="hotel",
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.room"
            ),
            preserve_default=False,
        ),
    ]
