# Generated by Django 5.1.4 on 2024-12-15 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_booking_hotel_booking_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="discount_price",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="price",
        ),
    ]
