# Generated by Django 5.1.4 on 2024-12-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_hotel_discount_price_remove_hotel_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
