# Generated by Django 5.1.4 on 2024-12-15 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_room_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="bed_type",
        ),
        migrations.RemoveField(
            model_name="room",
            name="capacity",
        ),
    ]
