# Generated by Django 5.1.4 on 2024-12-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_room_bed_type_remove_room_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="hotel",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.hotel"
            ),
            preserve_default=False,
        ),
    ]
